name: Conda package

on:
  push:
    branches:
      - main
  pull_request:

permissions: read-all

env:
  PACKAGE_NAME: intel-gpu-ocl-icd-system


jobs:
  build_and_test_linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Set pkgs_dirs
        run: |
          echo "pkgs_dirs: [~/.conda/pkgs]" >> ~/.condarc

      - name: Add conda to system path
        run: echo $CONDA/bin >> $GITHUB_PATH

      - name: Install conda-build
        run: conda install conda-build -c conda-forge --override-channels

      - name: Build conda package
        run: |
          # use bootstrap channel to pull NumPy linked with OpenBLAS
          CHANNELS="-c conda-forge --override-channels"
          conda build \
            $CHANNELS \
            conda-recipe

      - name: Upload artifact
        uses: actions/upload-artifact@v7.0.0
        with:
          name: ${{ env.PACKAGE_NAME }} ${{ runner.os }}
          path: /usr/share/miniconda/conda-bld/noarch/${{ env.PACKAGE_NAME }}-*.conda
